### ISSUE TITLE
Fine-tune on VQA

### ISSUE THREAD

**Issue by darwann** [zengyan-97/X-VLM#17]
Traceback (most recent call last):
  File "VQA.py", line 283, in <module>
    main(args, config)
  File "VQA.py", line 134, in main
    train_dataset, vqa_test_dataset = create_dataset('vqa', config, args.evaluate)
  File "/home/deer/X-VLM/dataset/__init__.py", line 84, in create_dataset
    vqa_test_dataset = vqa_dataset(config['test_file'], test_transform, config['vqa_root'], config['vg_root'],
  File "/home/deer/X-VLM/dataset/vqa_dataset.py", line 31, in __init__
    tokenizer = RobertaTokenizer.from_pretrained(text_encoder) if use_roberta else BertTokenizer.from_pretrained(text_encoder)
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1651, in from_pretrained
    fast_tokenizer_file = get_fast_tokenizer_file(
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3467, in get_fast_tokenizer_file
    all_files = get_list_of_files(
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/transformers/file_utils.py", line 1818, in get_list_of_files
    model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info(
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 94, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 98, in inner_f
    return f(*args, **kwargs)
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1289, in model_info
    hf_raise_for_status(r)
  File "/home/deer/anaconda3/envs/xvlm/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 242, in hf_raise_for_status
    **raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Tpjmanp6E_vsjeLwXkyXg)**

**Repository Not Found for url: https://huggingface.co/api/models/data/bert-base-uncased.**
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.

Hi, have you ever had this problem? how to deal with this problem.

**Comment by zengyan-97** [comment]
hi, 
you can try manually download "bert-base-uncased", and put it in data/.

**Comment by darwann** [comment]
> hi, you can try manually download "bert-base-uncased", and put it in data/.

Got it! Thanks
