### ISSUE TITLE
Error when Evaluating VQA with "model_state_epoch_9.th"

### ISSUE THREAD

**Issue by hujunming0625** [zengyan-97/X-VLM#35]
I encountered a problem when attempting to evaluate the VQA task using the "model_state_epoch_9.th" model. Here is a detailed description of the issue and relevant details.

```
Traceback (most recent call last):
  File "VQA.py", line 283, in <module>
    main(args, config)
  File "VQA.py", line 147, in main
    model.load_pretrained(args.checkpoint, config, is_eval=args.evaluate)
  File "/home/pod/shared-nvme/X-VLM/models/model_vqa.py", line 90, in load_pretrained
    msg = self.load_state_dict(state_dict, strict=False)
  File "/home/pod/shared-nvme/Anaconda/envs/VLM/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for XVLM:
        size mismatch for vision_encoder.layers.0.blocks.0.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 4]) from checkpoint, the shape in current model is torch.Size([529, 4]).
        size mismatch for vision_encoder.layers.0.blocks.0.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.0.blocks.1.attn_mask: copying a param with shape torch.Size([64, 225, 225]) from checkpoint, the shape in current model is torch.Size([64, 144, 144]).
        size mismatch for vision_encoder.layers.0.blocks.1.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 4]) from checkpoint, the shape in current model is torch.Size([529, 4]).
        size mismatch for vision_encoder.layers.0.blocks.1.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.1.blocks.0.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 8]) from checkpoint, the shape in current model is torch.Size([529, 8]).
        size mismatch for vision_encoder.layers.1.blocks.0.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.1.blocks.1.attn_mask: copying a param with shape torch.Size([16, 225, 225]) from checkpoint, the shape in current model is torch.Size([16, 144, 144]).
        size mismatch for vision_encoder.layers.1.blocks.1.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 8]) from checkpoint, the shape in current model is torch.Size([529, 8]).
        size mismatch for vision_encoder.layers.1.blocks.1.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.0.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.0.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.1.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.1.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.1.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.2.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.2.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.3.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.3.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.3.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.4.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.4.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.5.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.5.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.5.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.6.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.6.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.7.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.7.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.7.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.8.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.8.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.9.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.9.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.9.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.10.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.10.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.11.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.11.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.11.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.12.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.12.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.13.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.13.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.13.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.14.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.14.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.15.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.15.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.15.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.16.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.16.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.17.attn_mask: copying a param with shape torch.Size([4, 225, 225]) from checkpoint, the shape in current model is torch.Size([4, 144, 144]).
        size mismatch for vision_encoder.layers.2.blocks.17.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 16]) from checkpoint, the shape in current model is torch.Size([529, 16]).
        size mismatch for vision_encoder.layers.2.blocks.17.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.3.blocks.0.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 32]) from checkpoint, the shape in current model is torch.Size([529, 32]).
        size mismatch for vision_encoder.layers.3.blocks.0.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
        size mismatch for vision_encoder.layers.3.blocks.1.attn.relative_position_bias_table: copying a param with shape torch.Size([841, 32]) from checkpoint, the shape in current model is torch.Size([529, 32]).
        size mismatch for vision_encoder.layers.3.blocks.1.attn.relative_position_index: copying a param with shape torch.Size([225, 225]) from checkpoint, the shape in current model is torch.Size([144, 144]).
```
I'm a beginner, and it seems like I'm having an issue with 'mismatched training weight parameters'. Could you tell me how to resolve this problem?

**Comment by hujunming0625** [comment]
Resolved！
For `'VQA Checkpoints (16M)'`, you need to use `'./configs/VQA_480.yaml'` instead of `'./configs/VQA.yaml'`.
